---
- name: 'Assert'
  ansible.builtin.import_tasks: 'assert.yml'
- name: 'Annotate'
  ansible.builtin.import_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'
- name: 'Install'
  ansible.builtin.import_tasks: 'install.yml'
- name: 'Config'
  ansible.builtin.import_tasks: 'config.yml'

- name: 'Validate'
  when: not gcp_ddns_testing_enable
  ansible.builtin.import_tasks: 'validate.yml'
