---
###############################################################################
# Validate
###############################################################################
# Start Mox services if configuration deployed and confirm active and running.

- name: 'Validate | start services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
    daemon_reload: true
    state: 'restarted'
  failed_when: false
  loop:
    - 'gcp_ddns.service'

- name: 'Validate | query service status'
  ansible.builtin.service_facts:

- name: 'Validate | assert services running'
  ansible.builtin.assert:
    quiet: true
    that: ansible_facts.services[item].state == 'running'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                     Service failed to start.                      │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ {{ item }}
  loop:
    - 'gcp_ddns.service'
